name       : mutter
version    : 3.34.4
release    : 60
source     :
    - https://download.gnome.org/sources/mutter/3.34/mutter-3.34.4.tar.xz : 0134513515f605dd0858154d0b54d2e23c5779d52590533e266d407251e20ba2
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
setup      : |
    %apply_patches
    %meson_configure -Degl_device=true -Dinstalled_tests=false -Dprofiler=false -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
