name       : mutter
version    : '42.0'
release    : 87
source     :
    - https://download.gnome.org/sources/mutter/42/mutter-42.0.tar.xz : d1e240446b7f8cd8a3ff9daae336c1c9016193ba7e0769c79a5e6c03849022e5
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(graphene-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-eglstream)
    - pkgconfig(wayland-server)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - pkgconfig(xwayland)
    - zenity
rundeps    :
    - zenity
    - devel : mesalib-devel # Internal cogl requires EGL/eglmesaext.h from mesalib-devel
setup      : |
    %patch -p1 < $pkgfiles/0003-core-Disable-disastrous-NET_WM_PING-deletion-dialogs.patch
    %meson_configure \
        -Degl_device=true \
        -Dinstalled_tests=false \
        -Dprofiler=false \
        -Dtests=false \
        -Dwayland_eglstream=true
build      : |
    %ninja_build
install    : |
    %ninja_install
