name       : mutter
version    : 3.24.3
release    : 30
source     :
    - https://download.gnome.org/sources/mutter/3.24/mutter-3.24.3.tar.xz : 51a453b60b727adb11dcf70ba21ce7b8dccb38256d39ae06a1177118d5bea504
license    : LGPL-2.0
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
setup      : |
    %patch -p1 < $pkgfiles/0002-backends-native-Include-sysmacros.h-for-major-minor-.patch
    %patch -p1 < $pkgfiles/0003-Disable-disastrous-NET_WM_PING-deletion-dialogs.patch
    %configure --disable-static \
               --enable-introspection \
               --enable-egl-device
build      : |
    %make
install    : |
    %make_install
