name       : mutter
version    : 3.34.1
release    : 56
source     :
    - git|https://gitlab.gnome.org/GNOME/mutter.git : cf78598974b12be0d7fa67f6022abf0eac078b2b
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
setup      : |
    %apply_patches
    %meson_configure -Degl_device=true -Dprofiler=false
build      : |
    %ninja_build
install    : |
    %ninja_install
