name       : mutter
version    : 3.36.5
release    : 68
source     :
    - https://download.gnome.org/sources/mutter/3.36/mutter-3.36.5.tar.xz : e0d205a5cde665d39ed29833138b99323578baf65053d6b9de58bc7d33d6c7df
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(graphene-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
    - devel : mesalib-devel # Internal cogl requires EGL/eglmesaext.h from mesalib-devel
setup      : |
    %apply_patches
    %meson_configure -Degl_device=true -Dinstalled_tests=false -Dprofiler=false -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
