name       : mutter
version    : 3.22.2
release    : 21
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/mutter/3.22/mutter-3.22.2.tar.xz : d59b58356cba1165ef69a98f43e50777fded768860a9b118807c5a47274092a2
license    :
    - LGPL-2.0
summary    : Gnome Shell Window Manager
component  : desktop.gnome
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(sm)
    - pkgconfig(xcursor)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(gobject-introspection-1.0)
    - zenity
ccache     : no
rundeps    :
    - zenity
description: |
    Gnome Shell compositing window manager
setup      : |
    # https://bugzilla.gnome.org/show_bug.cgi?id=757661
    %patch -p1 < $pkgfiles/0001-backends-Ensure-reply-is-initialised-to-NULL.patch
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
