name       : mutter
version    : 3.32.0
release    : 46
source     :
    - https://download.gnome.org/sources/mutter/3.32/mutter-3.32.0.tar.xz : 7668a2208cb40f0f0c3a90dd72c3ea83993dbdfc24f517c6fa95abc04a8e1f19
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpipewire-0.2)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
setup      : |
    %apply_patches
    %meson_configure -Degl_device=true
build      : |
    %ninja_build
install    : |
    %ninja_install
