name       : mutter
version    : '41.1'
release    : 82
source     :
    - https://download.gnome.org/sources/mutter/41/mutter-41.1.tar.xz : 58e63fd0bc43f35134f21313aff4aebf92c829d6df4dc99a044a1e376691e3f3
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(graphene-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gudev-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-eglstream)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - pkgconfig(xwayland)
    - zenity
rundeps    :
    - zenity
    - devel : mesalib-devel # Internal cogl requires EGL/eglmesaext.h from mesalib-devel
setup      : |
    %apply_patches
    %meson_configure \
        -Degl_device=true \
        -Dinstalled_tests=false \
        -Dprofiler=false \
        -Dtests=false \
        -Dwayland_eglstream=true
build      : |
    %ninja_build
install    : |
    %ninja_install
