name       : mutter
version    : 3.24.1
release    : 24
source     :
    - https://download.gnome.org/sources/mutter/3.24/mutter-3.24.1.tar.xz : acaa77f9705cc6ca4a3d41935524ff31ba7a4c677bdd3e1d4662bbf3ece86a24
license    : LGPL-2.0
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : no
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xtst)
    - zenity
rundeps    :
    - zenity
setup      : |
    # https://bugzilla.gnome.org/show_bug.cgi?id=757661
    %patch -p1 < $pkgfiles/0001-backends-x11-Ensure-reply-is-initialised-to-NULL.patch
    %patch -p1 < $pkgfiles/0002-backends-native-Include-sysmacros.h-for-major-minor-.patch
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
