name        : mutter
version     : 3.18.1
release     : 16
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/mutter/3.18/mutter-3.18.1.tar.xz : 4fdee7c9dc2db3a48f18723f47c3122aa5bddaddb8751701ce243e577e2a69a9
license     :
    - LGPL-2.0
summary     : Gnome Shell Window Manager
builddeps   :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(sm)
    - pkgconfig(xcursor)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - zenity
ccache      : no
rundeps     :
    - zenity
description : |
    Gnome Shell compositing window manager
setup      : |
    # https://bugzilla.gnome.org/show_bug.cgi?id=757661
    %patch -p1 < $pkgfiles/0001-backends-Ensure-reply-is-initialised-to-NULL.patch
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install

 # backends/x11/meta-monitor-manager-xrandr.c
